[project]
build = "none"
strip_output = """
Use default settings!
"""
timeout = 30
capture_stderr = false

[[tests]]
name = "add-imm"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/add-imm-test.dig"]
expected = """
add-imm-test: passed
"""
rubric = 20

[[tests]]
name = "mov-imm"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/mov-imm-test.dig"]
expected = """
mov-imm-test: passed
"""
rubric = 20

[[tests]]
name = "sub-imm"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/sub-imm-test.dig"]
expected = """
sub-imm-test: passed
"""
rubric = 20

[[tests]]
name = "cumulative"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/cumulative-test.dig"]
expected = """
cumulative-test: passed
"""
rubric = 40
